# Finds if true.value is in interval.
# Will generate a vector of integers from 0 to 2,
# corresponding to the domains generated by the two limits.

#' True value in interval
#'
#' @param df A data frame containing the intervals to be evaluated.
#' @param lowLim the column index or name in the data frame `df`
#' corresponding to the lower limit of the interval.
#' @param upLim the column index or name in the data frame `df`
#' corresponding to the upper limit of the interval.
#' @param true.val the true value to be checked if it falls within
#' the interval defined by `lowLim` and `upLim`.
#'
#' @return a numeric vector of n elements with an integer value
#' for each interval of either 0 if the value is below the interval,
#' 1 if it is inside it (with a rightmost open limit)
#' and 2 if it is above the interval.
#' @export
#'
#' @examples
val_in_interval <- function(df, lowLim, upLim, true.val) {
  apply(
    df[, c(lowLim, upLim)],
    1, function(x) {
      x <- sort(x)
      findInterval(true.val, x)
    }
  )
}
